### ISSUE TITLE
This syntax does not work in Python 2.7

### ISSUE THREAD

**Issue by waypointsoftware** [twisted1919/mailwizz-python-sdk#5]
https://github.com/twisted1919/mailwizz-python-sdk/blob/669fd974382a8d61036e569f8c4a99838d045fa4/mailwizz/base.py#L28

What version of Python is required to make this library work. Also this fails:

from urllib.parse import urlparse

and this fails:

data = {**default, **data}

**Comment by waypointsoftware** [comment]
same problem here, had to go in and edit the code to make it work with 2.7.

**Comment by twisted1919** [comment]
You'll need Python >= 3.x
